### ISSUE TITLE
Explained Segment Markers

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/video50#102]
Via @dmalan and @dlloyd09:

When in Explained mode, highlight TOC hash marks on timeline wherever an explained segment is available by placing two white or gray dots above timeline marker, reminiscent of two heads (could even be the same icon, smaller). Ping if further clarification is needed! :)

**Comment by lukejacksonn** [comment]
I have implemented the fundamentals of this feature request.. that is, markers now appear on the timeline, showing where explained segments start, if they exist. The markers are gray dots but just one of them. There isn't really the space (or the resolution on non retina screens) to demonstrate clearly, two dots that allure to heads.

Obviously now that they are being rendered in place they can be styled however you like. What are you thoughts?

![image](https://cloud.githubusercontent.com/assets/1457604/25384748/a0fe73f8-29eb-11e7-8d46-aaa9dc71cf69.png)

**Comment by dmalan** [comment]
That works, so long as the dots only appear in Explained mode. Any reason the third dot doesn't line up with the hash mark perfectly, like the other two? Are the timecodes slightly different for the TOC and the Explained vid? @coltonoscopy

**Comment by lukejacksonn** [comment]
Implemented here https://github.com/cs50/video50/pull/119
