### ISSUE TITLE
Wrong Explained Icon

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/video50#103]
Via @dmalan and @dlloyd09:

Explained icon on bottom left should be two heads side by side, not overlapping.

**Comment by lukejacksonn** [comment]
I chose what I thought was the most fitting (according to the specification of two people side by side) icon from https://material.io/icons/ given that all the other icons used on the page are from that set. It would be nice to keep the style of icons consistent. Are there any other icons on https://material.io/icons/ that would be more suitable?

**Comment by dmalan** [comment]
Let's please just that one manually or such to achieve the side-by-side heads, as has always been the goal! Intent is to allude to Mystery Science Theater's side-by-side heads watching a video. Less important that it be a stock image.

**Comment by dmalan** [comment]
Do just comment with the PR, @coltonoscopy, when all set.

**Comment by coltonoscopy** [comment]
#130
