### ISSUE TITLE
Move Download Menu

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/video50#106]
Via @dmalan and @dlloyd09

Immediately to the left of full-screen icon, also remove "download" word, keeping only an icon. Also remove underlines from links.

**Comment by lukejacksonn** [comment]
This was moved for two reasons:

- It is not a video _control_ button, that is, it has no direct effect on the player/video which differentiated it from all the other buttons in the control bar (play, pause, next chapter, playback speed, fullscreen). It feels more like a meta operation which is more suited to the sidebar. 
- To save space in the control bar, especially on mobile, which is already very tight on space.

Have we received knowledge that users have been finding it hard to discover?

**Comment by dmalan** [comment]
It's just apples and oranges up there. Everything else up there relates to text, and more common for download buttons to be in the control bar. Indeed, much as those buttons control the video, so does clicking this particular button download the video. Let's indeed move down to bottom corner, per @coltonoscopy's spec.

**Comment by coltonoscopy** [comment]
Closed per #128
