### ISSUE TITLE
Android/iOS with Explained?

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/video50#109]
via @dmalan and @dlloyd09

What's possible with the explained functionality on a mobile device? Currently, the behavior as implemented likely wouldn't exist? Is it possible to implement some kind of similar behavior or workaround?

**Comment by lukejacksonn** [comment]
See comment on https://github.com/cs50/video50/issues/110 for explanation as to why this won't work. Also applies to multiscreen mode.

**Comment by lukejacksonn** [comment]
Action taken https://github.com/cs50/video50/pull/122 after discussion https://github.com/cs50/video50/issues/110
