### ISSUE TITLE
When side panel open, don't change icon to arrow, just change hamburger menu slightly

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/video50#112]
via @dmalan and @dlloyd09

Just odd that hamburger menu suddenly becomes an arrow :)

**Comment by lukejacksonn** [comment]
Swapping a hamburger into a `→` or `×` It is a pretty common UI pattern. Have we received knowledge that users have been misinterpreting the icon? If we were to _just change hamburger menu slightly_ what do you envision?

**Comment by dmalan** [comment]
An 'x' would be fine, but changing the hamburger to a right arrow suggests the hamburger itself should actually be a left arrow. Let's switch to an 'x' or somehow toggle the aesthetics of the hamburger to eliminate the unexpected semantics.

**Comment by coltonoscopy** [comment]
3ecb097
