### ISSUE TITLE
PiP window seems to be too large; not able to downscale sometimes

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/video50#115]
via @dmalan and @dlloyd09

Seems like the PiP window at times is not downscalable (per attached screenshot; couldn't scale it down after this point). Seems a little non-deterministic.

![image](https://cloud.githubusercontent.com/assets/3724177/25053728/ee235fb8-2126-11e7-9457-aef709875dc5.png)

**Comment by lukejacksonn** [comment]
Fixed by https://github.com/cs50/video50/pull/119
