### ISSUE TITLE
add 3/4 playbackRate icon to left of 1x playbackRate button

### ISSUE THREAD

**Issue by dmalan** [cs50/video50#126]
Looks like YouTube's added it to the web UI and, presumably, JS API.

<img width="877" alt="screen shot 2017-05-05 at 8 47 25 am" src="https://cloud.githubusercontent.com/assets/788678/25746015/7e887f04-316f-11e7-9ed4-44b115f8ae61.png">
<img width="298" alt="screen shot 2017-05-05 at 8 46 25 am" src="https://cloud.githubusercontent.com/assets/788678/25746014/7e87a1e2-316f-11e7-801f-56f5b7bcee85.png">

**Comment by coltonoscopy** [comment]
Implemented per #125
